---
# =============================================================================
# SSL VALIDATION - TRAEFIK INTEGRATION TESTING
# =============================================================================

- name: Test HTTP redirect (should redirect to HTTPS)
  ansible.builtin.uri:
    url: "http://{{ vault_traefik_domain }}"
    method: GET
    timeout: 30
    status_code: [301, 302]
    validate_certs: false
  register: http_redirect_test
  failed_when: false

- name: Test HTTPS access (main test)
  ansible.builtin.uri:
    url: "https://{{ vault_traefik_domain }}"
    method: GET
    timeout: 30
    validate_certs: false
    status_code: [200, 404, 502, 503]
  register: https_test
  failed_when: false

- name: Test external domain access via Traefik
  ansible.builtin.uri:
    url: "http://{{ vault_traefik_domain }}"
    method: GET
    timeout: 30
    status_code: [200, 301, 302, 404, 502, 503]
  register: external_test
  failed_when: false

- name: Display comprehensive test results
  ansible.builtin.debug:
    msg: |
      ==============================================================================
      TRAEFIK INTEGRATION TEST RESULTS
      ==============================================================================
      Internal Container Test: HTTP {{ internal_test.status }}
      Traefik Internal Test: HTTP {{ traefik_internal_test.status if traefik_internal_test.status is defined else 'N/A' }}
      External Domain Test: HTTP {{ external_test.status if external_test.status is defined else 'N/A' }}
      Host Header Test: HTTP {{ host_header_test.status if host_header_test.status is defined else 'N/A' }}
      HTTP Redirect Test: HTTP {{ http_redirect_test.status if http_redirect_test.status is defined else 'N/A' }}
      HTTPS Access Test: HTTP {{ https_test.status if https_test.status is defined else 'N/A' }}
      ==============================================================================
      {% if https_test.status == 200 %}
      SUCCESS: Traefik is serving your static web page!
      {% else %}
      WARNING: HTTPS test returned {{ https_test.status }}
      {% endif %}
      ==============================================================================
