---
# =============================================================================
# STATIC WEB PAGE DEPLOYMENT PLAYBOOK
# =============================================================================
# This playbook orchestrates the deployment of a static web page container
# and integrates it with the existing Traefik reverse proxy setup.
# =============================================================================

- name: Deploy Static Web Page with Traefik Integration
  hosts: vps
  become: false
  gather_facts: true

  roles:
    - role: deploy_static_web

- name: Test Traefik Integration and External Access
  hosts: vps
  become: false
  gather_facts: false

  tasks:
    - name: Display Traefik test configuration
      ansible.builtin.debug:
        msg: |
          ==============================================================================
          TRAEFIK INTEGRATION TESTING
          ==============================================================================
          Target Domain: {{ vault_traefik_domain }}
          Container Name: {{ static_web_container_name }}
          Expected Port: {{ static_web_port }}
          ==============================================================================

    - name: Verify static web container is running
      community.docker.docker_container_info:
        name: "{{ static_web_container_name }}"
      register: container_status
      failed_when:
        - not container_status.container
        - container_status.container.State.Status != "running"

    - name: Check Traefik container status
      community.docker.docker_container_info:
        name: traefik
      register: traefik_status
      ignore_errors: true

    - name: Check all containers in Traefik network
      community.docker.docker_container_info:
        name: "{{ item }}"
      loop:
        - "traefik"
        - "{{ static_web_container_name }}"
      register: all_containers

    - name: Display container network status
      ansible.builtin.debug:
        msg: |
          ==============================================================================
          CONTAINER STATUS CHECK
          ==============================================================================
          {% for container in all_containers.results %}
          Container: {{ container.container.Name if container.container else 'Not found' }}
          Status: {{ container.container.State.Status if container.container else 'Not running' }}
          Networks: {{ container.container.NetworkSettings.Networks.keys() | list if container.container else 'N/A' }}
          {% endfor %}
          ==============================================================================

    - name: Test internal container access (localhost)
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ static_web_port }}"
        method: GET
        timeout: 10
      register: internal_test
      failed_when: internal_test.status != 200

    - name: Test HTTP redirect (should redirect to HTTPS)
      ansible.builtin.uri:
        url: "http://{{ vault_traefik_domain }}"
        method: GET
        timeout: 30
        status_code: [301, 302]
        validate_certs: false
      register: http_redirect_test
      ignore_errors: true

    - name: Test HTTPS access (main test)
      ansible.builtin.uri:
        url: "https://{{ vault_traefik_domain }}"
        method: GET
        timeout: 30
        validate_certs: false
        status_code: [200, 404, 502, 503]
      register: https_test
      ignore_errors: true

    - name: Check Traefik logs for routing information
      ansible.builtin.shell: |
        docker logs traefik --tail=20
      register: traefik_logs
      changed_when: false
      ignore_errors: true

    - name: Check Traefik container labels and configuration
      community.docker.docker_container_info:
        name: traefik
      register: traefik_config
      ignore_errors: true

    - name: Display comprehensive test results
      ansible.builtin.debug:
        msg: |
          ==============================================================================
          TRAEFIK INTEGRATION TEST RESULTS
          ==============================================================================
          Internal Container Test: ✅ HTTP {{ internal_test.status }}
          HTTP Redirect Test: ✅ HTTP {{ http_redirect_test.status if http_redirect_test.status is defined else 'N/A' }}
          HTTPS Access Test: ✅ HTTP {{ https_test.status if https_test.status is defined else 'N/A' }}
          ==============================================================================
          {% if https_test.status == 200 %}
          🎉 SUCCESS: Traefik is serving your static web page!
          {% else %}
          ⚠️  WARNING: HTTPS test returned {{ https_test.status }}
          {% endif %}
          ==============================================================================

    - name: Show Traefik logs for debugging
      ansible.builtin.debug:
        msg: |
          ==============================================================================
          TRAEFIK LOGS (Last 20 lines)
          ==============================================================================
          {{ traefik_logs.stdout if traefik_logs.stdout else 'No logs available' }}
          ==============================================================================

    - name: Show Traefik container configuration
      ansible.builtin.debug:
        msg: |
          ==============================================================================
          TRAEFIK CONTAINER CONFIGURATION
          ==============================================================================
          Labels: {{ traefik_config.container.Config.Labels if traefik_config.container else 'Not available' }}
          Ports: {{ traefik_config.container.NetworkSettings.Ports if traefik_config.container else 'Not available' }}
          ==============================================================================
