---
# =============================================================================
# STATIC WEB PAGE DEPLOYMENT PLAYBOOK
# =============================================================================
# This playbook orchestrates the deployment of a static web page container
# and integrates it with the existing Traefik reverse proxy setup.
# =============================================================================

- name: Deploy Static Web Page with Traefik Integration
  hosts: vps
  become: false
  gather_facts: true

  roles:
    - role: deploy_static_web
