---
# =============================================================================
# TRAEFIK INTEGRATION TESTING PLAYBOOK
# =============================================================================
# This playbook tests if Traefik is properly serving the static web page
# and provides comprehensive diagnostics for the reverse proxy setup.
# =============================================================================

- name: Test Traefik Integration and External Access
  hosts: vps
  become: false
  gather_facts: true

  roles:
    - role: test_traefik_integration
